apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    fint.stack: administrasjon-kodeverk
    fint.role: provider
  name: provider-administrasjon-kodeverk
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: administrasjon-kodeverk
      fint.role: provider
  template:
    metadata:
      labels:
        fint.stack: administrasjon-kodeverk
        fint.role: provider
    spec:
      restartPolicy: Always
      containers:
        - name: provider-administrasjon-kodeverk
          image: fintlabs.azurecr.io/provider:PR-25.4
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /administrasjon/kodeverk/provider/health
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "500m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_OPTS
              value: "-Xmx1G"
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.events.orgIds
              value: health.fintlabs.no
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: administrasjon-kodeverk
            - name: fint.provider.assets.endpoint
              value: https://admin-beta.fintlabs.no/api/components/assets/administrasjon_kodeverk
            - name: server.context-path
              value: /administrasjon/kodeverk/provider
